version: '3'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: lasrwolff/ml-meetup:demo-api
    restart: always
    # IMPORTANT! for development only
    volumes:
      - ${PWD}/:/app/:rw
    ports:
      - 5000:5000
